# Generated by Django 4.2.21 on 2025-06-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_scan_scanresult_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanresult",
            name="status",
        ),
    ]
