# Generated by Django 4.2.21 on 2025-06-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_remove_scanresult_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanresult",
            name="scan_type",
            field=models.CharField(default="nmap", max_length=20),
            preserve_default=False,
        ),
    ]
